# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from flexium.proto import orchestrator_pb2 as flexium_dot_proto_dot_orchestrator__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flexium/proto/orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GPUOrchestratorStub(object):
    """GPU Orchestrator service for managing training processes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/flexium.GPUOrchestrator/Register',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.RegisterRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/flexium.GPUOrchestrator/Heartbeat',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Migrate = channel.unary_unary(
                '/flexium.GPUOrchestrator/Migrate',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.MigrateRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.MigrateResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/flexium.GPUOrchestrator/Unregister',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.UnregisterResponse.FromString,
                _registered_method=True)
        self.ListProcesses = channel.unary_unary(
                '/flexium.GPUOrchestrator/ListProcesses',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.ListProcessesRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.ListProcessesResponse.FromString,
                _registered_method=True)
        self.GetProcessStatus = channel.unary_unary(
                '/flexium.GPUOrchestrator/GetProcessStatus',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.GetProcessStatusRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.GetProcessStatusResponse.FromString,
                _registered_method=True)
        self.GetDeviceStatus = channel.unary_unary(
                '/flexium.GPUOrchestrator/GetDeviceStatus',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.GetDeviceStatusRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.GetDeviceStatusResponse.FromString,
                _registered_method=True)
        self.RequestErrorRecovery = channel.unary_unary(
                '/flexium.GPUOrchestrator/RequestErrorRecovery',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.ErrorRecoveryRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.ErrorRecoveryResponse.FromString,
                _registered_method=True)
        self.MarkGPUHealthy = channel.unary_unary(
                '/flexium.GPUOrchestrator/MarkGPUHealthy',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.MarkGPUHealthyRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.MarkGPUHealthyResponse.FromString,
                _registered_method=True)
        self.GetUnhealthyGPUs = channel.unary_unary(
                '/flexium.GPUOrchestrator/GetUnhealthyGPUs',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.GetUnhealthyGPUsRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.GetUnhealthyGPUsResponse.FromString,
                _registered_method=True)
        self.CompleteMigration = channel.unary_unary(
                '/flexium.GPUOrchestrator/CompleteMigration',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.CompleteMigrationRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.CompleteMigrationResponse.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/flexium.GPUOrchestrator/Pause',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.PauseRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.PauseResponse.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/flexium.GPUOrchestrator/Resume',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.ResumeRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.ResumeResponse.FromString,
                _registered_method=True)
        self.CompletePause = channel.unary_unary(
                '/flexium.GPUOrchestrator/CompletePause',
                request_serializer=flexium_dot_proto_dot_orchestrator__pb2.CompletePauseRequest.SerializeToString,
                response_deserializer=flexium_dot_proto_dot_orchestrator__pb2.CompletePauseResponse.FromString,
                _registered_method=True)


class GPUOrchestratorServicer(object):
    """GPU Orchestrator service for managing training processes
    """

    def Register(self, request, context):
        """Register a new training process with the orchestrator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Send periodic heartbeat to indicate process is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Migrate(self, request, context):
        """Request migration to a different device
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Unregister a process when it terminates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProcesses(self, request, context):
        """List all registered processes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessStatus(self, request, context):
        """Get status of a specific process
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStatus(self, request, context):
        """Get device utilization information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestErrorRecovery(self, request, context):
        """Request error recovery assistance (find suitable GPU after error)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkGPUHealthy(self, request, context):
        """Mark a GPU as healthy (manual recovery)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnhealthyGPUs(self, request, context):
        """Get list of unhealthy GPUs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteMigration(self, request, context):
        """Notify that migration is complete
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Pause a running process (checkpoint + free GPU)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Resume a paused process on a GPU
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompletePause(self, request, context):
        """Notify that pause is complete (checkpoint saved, GPU freed)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GPUOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.RegisterRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.HeartbeatRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Migrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Migrate,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.MigrateRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.MigrateResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.UnregisterRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.UnregisterResponse.SerializeToString,
            ),
            'ListProcesses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProcesses,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.ListProcessesRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.ListProcessesResponse.SerializeToString,
            ),
            'GetProcessStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessStatus,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.GetProcessStatusRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.GetProcessStatusResponse.SerializeToString,
            ),
            'GetDeviceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStatus,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.GetDeviceStatusRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.GetDeviceStatusResponse.SerializeToString,
            ),
            'RequestErrorRecovery': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestErrorRecovery,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.ErrorRecoveryRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.ErrorRecoveryResponse.SerializeToString,
            ),
            'MarkGPUHealthy': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkGPUHealthy,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.MarkGPUHealthyRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.MarkGPUHealthyResponse.SerializeToString,
            ),
            'GetUnhealthyGPUs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnhealthyGPUs,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.GetUnhealthyGPUsRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.GetUnhealthyGPUsResponse.SerializeToString,
            ),
            'CompleteMigration': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteMigration,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.CompleteMigrationRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.CompleteMigrationResponse.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.PauseRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.PauseResponse.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.ResumeRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.ResumeResponse.SerializeToString,
            ),
            'CompletePause': grpc.unary_unary_rpc_method_handler(
                    servicer.CompletePause,
                    request_deserializer=flexium_dot_proto_dot_orchestrator__pb2.CompletePauseRequest.FromString,
                    response_serializer=flexium_dot_proto_dot_orchestrator__pb2.CompletePauseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flexium.GPUOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flexium.GPUOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GPUOrchestrator(object):
    """GPU Orchestrator service for managing training processes
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/Register',
            flexium_dot_proto_dot_orchestrator__pb2.RegisterRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/Heartbeat',
            flexium_dot_proto_dot_orchestrator__pb2.HeartbeatRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Migrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/Migrate',
            flexium_dot_proto_dot_orchestrator__pb2.MigrateRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.MigrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/Unregister',
            flexium_dot_proto_dot_orchestrator__pb2.UnregisterRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.UnregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProcesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/ListProcesses',
            flexium_dot_proto_dot_orchestrator__pb2.ListProcessesRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.ListProcessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/GetProcessStatus',
            flexium_dot_proto_dot_orchestrator__pb2.GetProcessStatusRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.GetProcessStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/GetDeviceStatus',
            flexium_dot_proto_dot_orchestrator__pb2.GetDeviceStatusRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.GetDeviceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestErrorRecovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/RequestErrorRecovery',
            flexium_dot_proto_dot_orchestrator__pb2.ErrorRecoveryRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.ErrorRecoveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkGPUHealthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/MarkGPUHealthy',
            flexium_dot_proto_dot_orchestrator__pb2.MarkGPUHealthyRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.MarkGPUHealthyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnhealthyGPUs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/GetUnhealthyGPUs',
            flexium_dot_proto_dot_orchestrator__pb2.GetUnhealthyGPUsRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.GetUnhealthyGPUsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteMigration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/CompleteMigration',
            flexium_dot_proto_dot_orchestrator__pb2.CompleteMigrationRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.CompleteMigrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/Pause',
            flexium_dot_proto_dot_orchestrator__pb2.PauseRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.PauseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/Resume',
            flexium_dot_proto_dot_orchestrator__pb2.ResumeRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.ResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompletePause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flexium.GPUOrchestrator/CompletePause',
            flexium_dot_proto_dot_orchestrator__pb2.CompletePauseRequest.SerializeToString,
            flexium_dot_proto_dot_orchestrator__pb2.CompletePauseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
